languageCode = "en-us"
title = "Nasty Tester"
baseurl = "https://nastytester.com/"
theme = "beautifulhugo"
copyright = "Nasty Tester"
pygmentsStyle = "xcode"
uglyUrls = true
comments = true
googleAnalytics = "UA-130401599-1"
mainSections = ["posts"]

[services]
  [services.disqus]
    shortname = "nasty-tester"

[params]
  useHLJS = true
  paginatedsections = ["posts"]
  description = "When testing gets nasty..."
  metadescription = "Blog about technical things and thinking outside the box"
  mainSections = ["posts"]
  [params.author]
    name = "Max Norin"
    github = "mnorin"
    linkedin = "mnorin"
    telegram = "@maxnorin"

[menu]
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    title = "Tags"
    url = "/tags.html"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts section"
    url = "posts.html"
    weight = -110

[caches]
  [caches.images]
    dir = ':cacheDir/images'

